# Generated by Django 2.2.4 on 2019-08-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0004_auto_20190810_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Dogs', 'Dogs'), ('Cats', 'Cats')], max_length=128, unique=True),
        ),
    ]
