# Generated by Django 2.2.4 on 2019-08-11 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0006_auto_20190810_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogging.Category')),
                ('post_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogging.Post')),
            ],
        ),
    ]
