# Generated by Django 2.2.4 on 2019-08-12 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0007_postcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='post_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blogging.Post'),
        ),
    ]
