# Generated by Django 2.2.4 on 2019-08-12 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0008_auto_20190811_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='post_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogging.Post'),
        ),
    ]
