# Generated by Django 2.2.4 on 2019-08-15 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0009_auto_20190811_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategory',
            old_name='cat_name',
            new_name='category_name',
        ),
    ]
